name: PerlMaple
version: 0.02
abstract: Perl binding for Waterloo's Maple software
author: Agent Zhang <agent2002@126.com>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  Test::Deep: 0
requires:
  Carp: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
