name: PerlMaple
version: 0.01
abstract: Perl binding for Waterloo's Maple on Win32
author: Agent Zhang <agent2002@126.com>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Inline: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
