
abstract: Perl binding for Waterloo's Maple software
author: Agent Zhang, <agentzh@gmail.com>
build_requires: 
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.55
license: perl
name: PerlMaple
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  perl: 5.6.0
version: 0.03
